PERFORMER ""
TITLE "Test Mix"
FILE "Test Mix.mp3" MP3
TRACK 1 AUDIO
  TITLE "First Track"
  PERFORMER "Tester"
  INDEX 01 00:00:00
TRACK 2 AUDIO
  TITLE "Second Track"
  PERFORMER "Tester"
  INDEX 01 00:18:00
